Repository art-here/art-here-frontend, pull requests merged in 2023-05, with the labels that each got.

#48 [feat] 지도 페이지 기능 및 UI 개선 ( 드래그 이벤트 추가)
  .env.d.ts
  public/favicon.ico
  src/component/Categories/View/index.tsx
  src/component/Categories/index.tsx
  src/component/Common/Header/View/HeaderView.tsx
  src/component/Common/Loader/View/index.tsx
  src/component/Searcher/View/index.tsx
  src/component/Searcher/index.tsx
  src/component/Searcher/types.ts
  src/component/Sorter/View/index.tsx
  src/component/Sorter/index.tsx
  src/constants/categories.ts
  src/constants/index.ts
  src/constants/map.ts
  src/hooks/Gallery/useGetThumbnails.tsx
  src/hooks/Map/useArtInfo.tsx
  src/hooks/Map/useArtsOnMap.tsx
  src/hooks/Search/useSearchGallery.tsx
  src/hooks/useGetUserLocation.tsx
  src/main.tsx
  src/pages/Home/Gallery/Gallery.tsx
  src/pages/Home/Gallery/GalleryHOC.tsx
  src/pages/Home/Gallery/View/ThumbnailView.tsx
  src/pages/Home/Gallery/View/index.tsx
  src/pages/Home/Gallery/index.tsx
  src/pages/Home/Gallery/types.ts
  src/pages/Home/Map/MyLocation.tsx
  src/pages/Home/Map/View/ArtInfoView.tsx
  src/pages/Home/Map/View/MyLocationView.tsx
  src/pages/Home/Map/View/OverlayView.tsx
  src/pages/Home/Map/View/index.tsx
  src/pages/Home/Map/index.tsx
  src/pages/Home/Map/types.ts
  src/pages/Home/View/index.tsx
  src/pages/NotFound/types.ts
  src/pages/OAuth/index.tsx
  src/pages/Search/index.tsx
  src/pages/Signup/types.ts
  src/services/auth/index.ts
  src/services/cacheKeys.ts
  src/services/image/index.ts
  src/services/map/index.ts
  src/services/search/index.ts
  src/store/gallery.ts
  src/styles/theme.ts
Labels: feat

#55 [feat]: 검색 및 정렬 기능 구현 #30
  src/hooks/Admin/useGetAdminArt.ts
  src/pages/Admin/CreateArt/View/index.tsx
  src/pages/Admin/MyArt/View/index.tsx
  src/pages/Admin/MyArt/index.tsx
  src/pages/Admin/MyArt/types.ts
  src/pages/Admin/Sidebar/View/index.tsx
  src/pages/Admin/View/index.tsx
  src/services/admin/index.ts
  src/services/cacheKeys.ts
  src/styles/glabalstyle.ts
Labels: feat

#49 [fix] 검색시 중복 경로 오류 수정 및 누락된 idx 파라미터 추가
  src/component/Categories/index.tsx
  src/component/Searcher/index.tsx
  src/component/Sorter/index.tsx
  src/component/Welcome/HeroSection/index.tsx
  src/constants/art/rate.ts
  src/constants/router.ts
  src/hooks/Gallery/useGetThumbnails.tsx
  src/hooks/Map/useArtInfo.tsx
  src/hooks/Map/useArtsOnMap.tsx
  src/hooks/Search/useSearchGallery.tsx
  src/hooks/useGetUserLocation.tsx
  src/main.tsx
  src/pages/Admin/CreateArt/View/index.tsx
  src/pages/Admin/Sidebar/View/index.tsx
  src/pages/Art/ArtAccount/View/index.tsx
  src/pages/Art/ArtRate/View/index.tsx
  src/pages/Art/ArtRate/index.tsx
  src/pages/Art/ArtRate/types.ts
  src/pages/Art/ArtReviews/View/index.tsx
  src/pages/Art/ArtReviews/index.tsx
  src/pages/Art/ArtReviews/types.ts
  src/pages/Art/View/index.tsx
  src/pages/Art/index.tsx
  src/pages/Arts/Gallery/GalleryHOC.tsx
  src/pages/Arts/Gallery/View/ThumbnailView.tsx
  src/pages/Arts/Gallery/View/index.tsx
  src/pages/Arts/Gallery/index.tsx
  src/pages/Arts/Gallery/types.ts
  src/pages/Arts/Map/ArtInfo.tsx
  src/pages/Arts/Map/MyLocation.tsx
  src/pages/Arts/Map/Overlay.tsx
  src/pages/Arts/Map/View/ArtInfoView.tsx
  src/pages/Arts/Map/View/MyLocationView.tsx
  src/pages/Arts/Map/View/OverlayView.tsx
  src/pages/Arts/Map/View/index.tsx
  src/pages/Arts/Map/index.tsx
  src/pages/Arts/Map/types.ts
  src/pages/Arts/index.tsx
  src/pages/Home/Gallery/Gallery.tsx
  src/pages/Home/Map/MyLocation.tsx
  src/pages/Home/index.tsx
  src/pages/NotFound/index.tsx
  src/pages/OAuth/index.tsx
  src/pages/Search/index.tsx
  src/services/cacheKeys.ts
  src/services/gallery/index.ts
  src/services/image/index.ts
  src/services/map/index.ts
  src/services/search/index.ts
  src/store/gallery.ts
  src/styles/theme.ts
Labels: fix

#60 [feat] 작품 계정 내 별점, 게시물수, 만족도 조회
  src/constants/art/satisfaction.ts
  src/pages/Admin/CreateArt/View/index.tsx
  src/pages/Art/ArtAccount/View/index.tsx
  src/pages/Art/ArtAccount/index.tsx
  src/pages/Art/ArtReviews/index.tsx
  src/pages/Art/ArtSatisfaction/View/index.tsx
  src/pages/Art/ArtSatisfaction/index.tsx
  src/pages/Art/ArtSatisfaction/types.ts
  src/pages/Art/View/index.tsx
  src/pages/Art/hooks/useArtSatisfaction.tsx
  src/pages/Art/hooks/useIdFromParam.tsx
  src/pages/Art/index.tsx
  src/pages/Art/types.ts
  src/services/art/satisfaction.ts
  src/services/cacheKeys.ts
  src/utils/getSortedSatisfaction.ts
Labels: feat

#62 [fix] 사용자 위치 미허용시 중심 위치 서울 중구로 수정
  src/hooks/Map/useGetUserLocation.tsx
  src/pages/Arts/Map/index.tsx
Labels: fix

#61 [design] 랜딩 페이지 내 서비스 설명 추가
  index.html
  public/assets/images/introduction_arts.png
  public/assets/images/introduction_map.png
  public/assets/images/introduction_review.png
  public/vite.svg
  src/component/Categories/View/index.tsx
  src/component/Common/Header/View/HeaderView.tsx
  src/component/Common/Header/View/NavbarView.tsx
  src/component/Common/Header/View/UserbarView.tsx
  src/component/Common/Layout/View/LayoutView.tsx
  src/component/Searcher/View/index.tsx
  src/component/Sorter/View/index.tsx
  src/component/Welcome/HeroSection/index.tsx
  src/constants/index.ts
  src/constants/router.ts
  src/hooks/Gallery/useGetThumbnails.tsx
  src/main.tsx
  src/pages/Arts/Gallery/View/ThumbnailView.tsx
  src/pages/Arts/Gallery/View/index.tsx
  src/pages/Arts/Map/View/MyLocationView.tsx
  src/pages/Arts/Map/View/index.tsx
  src/services/image/index.ts
Labels: design
