Repository art-here/art-here-frontend, pull requests merged in 2023-03, with the labels that each got.

#17 fix: 타입 관련 .env.d.ts 파일 gitignore에서 제외
  .env.d.ts
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/constants/index.ts
  src/hooks/Gallery/useGetImages.tsx
  src/hooks/Gallery/useGetThumbnails.tsx
  src/hooks/Gallery/useNextImages.tsx
  src/pages/Home/Gallery/View/index.tsx
  src/pages/Home/Gallery/index.tsx
  src/pages/Home/Gallery/types.ts
  src/services/api/gallery/index.ts
  src/services/image/getImageURL.ts
  src/services/image/index.ts
  src/services/map/index.ts
  vite.config.ts
Labels: bug

#19 fix: 지도 상 작품 정보 타입 수정
  src/hooks/Map/useArtsOnMap.tsx
  src/pages/Home/Gallery/types.ts
  src/pages/Home/Map/types.ts
  src/services/map/index.ts
Labels: bug

#21 [test] 로그인 쿠키 실행 관련 테스팅
  package-lock.json
  package.json
  src/assets/react.svg
  src/component/Common/Header/Userbar.tsx
  src/constants/index.ts
  src/hooks/Gallery/useGetImages.tsx
  src/hooks/Gallery/useNextImages.tsx
  src/main.tsx
  src/pages/Auth/index.tsx
  src/pages/OAuth/index.tsx
  src/services/image/index.ts
Labels: feat

#22 [feat] gallery view 내 무한 스크롤 구현
  package-lock.json
  package.json
  src/component/Common/Header/Userbar.tsx
  src/hooks/Gallery/useGetImages.tsx
  src/main.tsx
  src/pages/Home/Gallery/Thumbnail.tsx
  src/pages/Home/Gallery/View/ThumbnailView.tsx
  src/pages/Home/Gallery/View/index.tsx
  src/pages/Home/Gallery/index.tsx
  src/pages/OAuth/index.tsx
  src/services/image/index.ts
Labels: feat, fix

#26 [design]: 공통 레이아웃 컴포넌트 생성 및 글로벌 스타일 설정
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/component/Common/Layout/View/LayoutView.tsx
  src/component/Common/Layout/index.tsx
  src/component/Common/Layout/types.ts
  src/constants/router.ts
  src/main.tsx
  src/pages/Admin/Art/CreateArt/index.tsx
  src/pages/Admin/Art/CreateArt/view/index.tsx
  src/pages/Admin/Art/View/index.tsx
  src/pages/Admin/Art/index.tsx
  src/pages/Admin/Sidebar/View/index.tsx
  src/pages/Admin/Sidebar/index.tsx
  src/pages/Admin/View/index.tsx
  src/pages/Admin/index.tsx
  src/pages/Home/View/index.tsx
  src/styles/glabalstyle.ts
  src/styles/theme.ts
Labels: chore

#28 [fix] 메인 페이지 내 갤러리, 지도 컴포넌트 누락 수정
  src/App.tsx
  src/component/Common/Header/Userbar.tsx
  src/component/Common/Layout/View/LayoutView.tsx
  src/component/Common/Layout/index.tsx
  src/component/Searcher/View/index.tsx
  src/component/Searcher/index.tsx
  src/component/Searcher/types.ts
  src/constants/index.ts
  src/hooks/Gallery/useGetImages.tsx
  src/hooks/Gallery/useNextImages.tsx
  src/hooks/Gallery/useSearchByName.tsx
  src/hooks/useRouter.tsx
  src/main.tsx
  src/pages/Home/Gallery/View/index.tsx
  src/pages/Home/Gallery/index.tsx
  src/pages/Home/View/index.tsx
  src/pages/OAuth/index.tsx
  src/pages/Search/index.tsx
  src/services/api/gallery/index.ts
  src/services/api/index.ts
Labels: fix
