Repository art-here/art-here-frontend, pull requests merged in 2023-04, with the labels that each got.

#31 [feat] 갤러리 페이지 내 검색 기능 구현
  package-lock.json
  package.json
  src/component/Searcher/index.tsx
  src/hooks/Gallery/useGetThumbnails.tsx
  src/hooks/Gallery/useSearchByName.tsx
  src/hooks/Search/useSearchGallery.tsx
  src/main.tsx
  src/pages/Home/Gallery/GalleryHOC.tsx
  src/pages/Home/Gallery/View/index.tsx
  src/pages/Home/Gallery/index.tsx
  src/pages/Home/Gallery/types.ts
  src/pages/Search/index.tsx
  src/services/cacheKeys.ts
  src/store/gallery.ts
Labels: feat

#40 [feat] 로그인 안내 페이지 구현
  package-lock.json
  package.json
  src/component/Common/Header/Userbar.tsx
  src/component/Common/Header/View/UserbarView.tsx
  src/component/Common/Header/types.ts
  src/constants/router.ts
  src/hooks/Auth/token.tsx
  src/main.tsx
  src/pages/Signup/View/index.tsx
  src/pages/Signup/index.tsx
  src/pages/Signup/types.ts
  src/services/auth/index.ts
Labels: feat

#46 [fix] refetchOnWindowFocus로 인한 데이터 중복 오류 수정 및 불필요한 Thumbnail 컴포넌트 삭제
  src/main.tsx
  src/pages/Home/Gallery/Thumbnail.tsx
  src/pages/Home/Gallery/View/ThumbnailView.tsx
  src/pages/Home/Gallery/View/index.tsx
Labels: fix

#53 [design] 랜딩 페이지 UI 구현 #45
  font.d.ts
  public/assets/fonts/ShadowsIntoLight.ttf
  public/assets/images/background.jpg
  src/component/Common/Header/Header.tsx
  src/component/Common/Header/View/HeaderView.tsx
  src/component/Common/Header/View/NavbarView.tsx
  src/component/Common/Header/View/UserbarView.tsx
  src/component/Common/Layout/View/LayoutView.tsx
  src/component/Welcome/HeroSection/index.tsx
  src/component/Welcome/View/index.tsx
  src/component/Welcome/index.tsx
  src/styles/glabalstyle.ts
  src/styles/theme.ts
Labels: design
